metrics:
# Интервал сбора метрик.
  scrape_interval: 30s
# Интервал повторных попыток при ошибке.  
  retry_interval: 10s

kafka:
  brokers:
    - "192.168.41.36:9092"
    - "192.168.41.37:9092"
    - "192.168.41.38:9092"
    - "192.168.41.48:9092"
    - "192.168.41.104:9092"
    - "192.168.41.106:9092"
  sasl:
    enabled: true
    # Флаг, указывающий на необходимость выполнения рукопожатия SASL перед отправкой запроса (default: true).
    handshake: true 
    mechanism: "PLAIN"
    username: "broker"
    password: "ec7H3zwCJyfWxkrm"
  tls:
    enabled: false
  timeout:
    # DialTimeout - максимальное время ожидания при установке TCP-соединения с брокером. Если за это время соединение не установлено, возникнет ошибка. 
    dial: 10s
    # ReadTimeout - максимальное время ожидания при чтении ответа от брокера.
    read: 10s
    # WriteTimeout - максимальное время ожидания при отправке запроса брокеру.
    write: 10s

# Порт, на котором будет запущен экспортер
exporterPort: 9877
